x-common-config:
  &common-config
  restart: unless-stopped
  network_mode: host
  ipc: host
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # *
  volumes:
    - /etc/group:/etc/group:ro                  # *
    - /etc/passwd:/etc/passwd:ro                # *
    - /etc/shadow:/etc/shadow:ro                # *
    - /home/husarion/.ros:/home/husarion/.ros   # *
    - ${FASTRTPS_DEFAULT_PROFILES_FILE:-dummy_volume_fastdds}:${FASTRTPS_DEFAULT_PROFILES_FILE:-/dummy_volume_fastdds}:ro  # **
    - ${CYCLONEDDS_PATH:-dummy_volume_cyclonedds}:${CYCLONEDDS_PATH:-/dummy_volume_cyclonedds}:ro                          # **
  environment:
    - RMW_IMPLEMENTATION              # ***
    - FASTRTPS_DEFAULT_PROFILES_FILE  # ***
    - CYCLONEDDS_URI                  # ***
    - ROS_DOMAIN_ID                   # ***

services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble-0.8.2-20230913
    container_name: rosbot-xl
    <<: *common-config
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    container_name: microros
    <<: *common-config
    environment: #only two envs are valid for micro-xrce-agent
      - FASTRTPS_DEFAULT_PROFILES_FILE            # ***
      - XRCE_DOMAIN_ID_OVERRIDE=${ROS_DOMAIN_ID:-}  # ***
    command: MicroXRCEAgent udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20230427
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230505-stable
    ports:
      - 9090:9090
    <<: *common-config
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  foxglove:
    image: husarion/foxglove:humble-1.39.1-20230220
    ports:
      - 8080:8080
    volumes:
      - ./config/rosbot_xl_sensors_foxglove.json:/src/FoxgloveDefaultLayout.json
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090

volumes:
  dummy_volume_fastdds:
  dummy_volume_cyclonedds:
