services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    command: MicroXRCEAgent udp4 --port 8888 # -v6

  rplidar:
    image: husarion/rplidar:humble
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230505-stable
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  foxglove:
    image: husarion/foxglove:humble-1.39.1-20230220
    ports:
      - 8080:8080
    volumes:
      - ./config/rosbot_xl_sensors_foxglove.json:/src/FoxgloveDefaultLayout.json
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090